# Welcome to Jekyll!
#

# Site settings
title: stylejar
description: |
  If it ain't raining, it ain't training!
owner: p4 # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: phnessu4@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.stylejar.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/phnessu4
  github: https://github.com/phnessu4
  dribbble: https://dribbble.com/phnessu4
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/phnessu4
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  weibo: http://weibo.com/1756735715
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
# Time zone
timezone: asia/shanghai
# Encoding
encoding: utf-8
